name: Build 

on:
  pull_request: 
        types: [ opened, edited, synchronize, reopened ] 

jobs:
  GithubTest:
    name: TiCS
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: TICS Action Run
        uses: tiobe/tics-github-action@main
        env: 
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          TICSAUTHTOKEN: 'YjRjM2E1NjgtMGFiZi00MTAwLTk0MzQtY2MxYjZhZDUzYjdjOnVyaXI3WUZycVkyYzZwcQ'
        with:
          projectName: 'cpp-game-vs'
          branchName: 'trunk'
          ticsConfiguration: 'http://192.168.1.117:42506/tiobeweb/TICS/api/cfg?name=default'
          calc: 'GATE'
          clientToken: 'YjRjM2E1NjgtMGFiZi00MTAwLTk0MzQtY2MxYjZhZDUzYjdjOnVyaXI3WUZycVkyYzZwcQ'
          tmpDir: 'C:\BitBucket\RobotFramework\tmp\30696\cpp-game-vs'
          
